### ISSUE TITLE
Nx build command failure

### ISSUE THREAD

**Issue by manandkumaar** [nxkit/nxkit#119]
### Current Behavior

muruga6@C001858566 A-Blocks % nx run blocks-design-tokens:build

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

**with --verbose flag -** 

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/eslint/plugin plugin.
    - libs/blocks-design-tokens/eslint.config.js: baseConfig is not iterable
      TypeError: baseConfig is not iterable
          at Object.<anonymous> (/Users/muruga6/Workspace/CAT-Digital/A-Blocks/libs/blocks-design-tokens/eslint.config.js:4:6)
          at Module._compile (node:internal/modules/cjs/loader:1469:14)
          at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
          at Module.load (node:internal/modules/cjs/loader:1288:32)
          at Module._load (node:internal/modules/cjs/loader:1104:12)
          at cjsLoader (node:internal/modules/esm/translators:346:17)
          at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
          at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
          at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
          at async loadConfigFile (/Users/muruga6/Workspace/CAT-Digital/A-Blocks/node_modules/eslint/lib/config/config-loader.js:202:21)

As per nx plugin doc- nxkit plugin supports v19.x to v21.x  
![image](https://github.com/user-attachments/assets/b8f8277a-2ceb-40ee-8c77-3bf1e362056b)

### Expected Behaviour

All nx and nxkit commands should work file

### Steps to Reproduce

Node - v20.17.0
Nx Version: Local: v20.0.3, Global: v20.1.2
"style-dictionary": "^4.1.3",

1. npm install -D @nxkit/style-dictionary
2. nx generate @nxkit/style-dictionary:lib multi-design-tokens
3. Select **multiconfig** option for cmd prompt - Which project preset would you like to use?
4. nx run blocks-design-tokens:build

### Nx Report

```shell
Node           : 20.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.22.22

nx (global)        : 20.1.2
nx                 : 20.0.3
@nx/js             : 20.0.3
@nx/jest           : 20.0.3
@nx/eslint         : 20.0.3
@nx/workspace      : 20.0.3
@nx/angular        : 20.0.3
@nx/devkit         : 20.0.3
@nx/eslint-plugin  : 20.0.3
@nx/next           : 20.0.3
@nx/react          : 20.0.3
@nx/web            : 20.0.3
@nx/webpack        : 20.0.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/next/plugin
---------------------------------------
Community plugins:
@nxkit/style-dictionary : 6.0.0
---------------------------------------
⚠️ Unable to construct project graph.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/eslint/plugin plugin.
    - libs/blocks-design-tokens/eslint.config.js: baseConfig is not iterable
      TypeError: baseConfig is not iterable
          at Object.<anonymous> (/Users/muruga6/Workspace/CAT-Digital/A-Blocks/libs/blocks-design-tokens/eslint.config.js:4:6)
          at Module._compile (node:internal/modules/cjs/loader:1469:14)
          at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
          at Module.load (node:internal/modules/cjs/loader:1288:32)
          at Module._load (node:internal/modules/cjs/loader:1104:12)
          at cjsLoader (node:internal/modules/esm/translators:346:17)
          at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
          at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
          at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
          at async loadConfigFile (/Users/muruga6/Workspace/CAT-Digital/A-Blocks/node_modules/eslint/lib/config/config-loader.js:202:21)
```

### Failure Logs

```shell
muruga6@C001858566 A-Blocks % npx nx run blocks-design-tokens:build

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

muruga6@C001858566 A-Blocks % nx reset

 NX   Resetting the Nx cache and stopping the daemon.



 NX   Successfully reset the Nx workspace.

muruga6@C001858566 A-Blocks % nx run blocks-design-tokens:build

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

muruga6@C001858566 A-Blocks % nx run blocks-design-tokens:build --verbose

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/eslint/plugin plugin.
    - libs/blocks-design-tokens/eslint.config.js: baseConfig is not iterable
      TypeError: baseConfig is not iterable
          at Object.<anonymous> (/Users/muruga6/Workspace/CAT-Digital/A-Blocks/libs/blocks-design-tokens/eslint.config.js:4:6)
          at Module._compile (node:internal/modules/cjs/loader:1469:14)
          at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
          at Module.load (node:internal/modules/cjs/loader:1288:32)
          at Module._load (node:internal/modules/cjs/loader:1104:12)
          at cjsLoader (node:internal/modules/esm/translators:346:17)
          at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
          at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
          at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
          at async loadConfigFile (/Users/muruga6/Workspace/CAT-Digital/A-Blocks/node_modules/eslint/lib/config/config-loader.js:202:21)

muruga6@C001858566 A-Blocks %
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manandkumaar** [comment]
Ahh.. just noticed that there is a bug open to support  style-dictionary v4 already. 
https://github.com/nxkit/nxkit/issues/113

So, closing my duplicate ticket. Thanks
